### ISSUE TITLE
How to identify Score

### ISSUE THREAD

**Issue by MPult** [Thimbleby/DigitSpan#1]
how yould you see at what question length the score is below 100% for the first time?
ps: love the project

**Comment by Thimbleby** [comment]
Thank you for your interest!

It has been awhile since I've looked at this code, apologies if I'm rusty, though I am happy to help.

At the end of the test it presents the results, such as in the example below:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/10994037/74634298-74b34180-515b-11ea-8ab8-44454b363cec.png">

If you had it download the results, or similar, it would produce the raw data in JSON, including time taken, though I don't think it currently includes any calculated results, unlike the scores shown above.
Are you asking for an automated way of including calculated results, including specifically the first non 100% result in datatosubmit?
Or about displaying that result when the test is finished?

The output that is downloaded is in the variable called 'dataToSubmit' inside the main() function near the end of main.js.
The code controlling the results shown to the user are in the finishText svg lines above it - which start fairly close to the beginning of the main() function.

**Comment by MPult** [comment]
Yes I want to store the first non 100% result in a cookie (at what question the user did not get 100%)

**Comment by Thimbleby** [comment]
Assuming you would like it stored when the test is over, rather than ending the test immediately. 
I've uploaded some code that should make it easier.

Down towards the end of the code, in the main() function, I print the results of a new function firstIncorrect(). This returns the array indices of the first incorrectly answered response. This means that it starts counting at 0, although note that the first two items cannot be answered incorrectly.

**Comment by MPult** [comment]
Thank you very much, this is much cleaner than my series of 9 if statements.

At what point of time does "endCriteria" become true?

**Comment by Thimbleby** [comment]
It ends either when every item is completed, or the user's success rate has become consistently extremely low.

The current definition of 'extremely low', is in the later half of the scoreTest() function. In other words, whenever the code calls the function to determine how good the user's previous response was, it evaluates if the test should end early.

This was done to try and avoid situations where low ability users were pointlessly taking test items that just made them feel bad, and didn't give the investigator any new information.

I haven't checked what exactly state I uploaded it in, but the last time I used it I set that early cut-off to be on what I felt was leaned towards giving the user more test items than was necessarily needed.

**Comment by Thimbleby** [comment]
The number of items - and their length is defined in the questionLengths array. The first sub array are practice items, and the second is real items. 

I think in practice for my own use I used 
var questionLengths = [[2,3],[3,4,4,5,5,6,6,7,7,8,8,9,9,10,11]];

What you will want to use will likely depend on how much information you want, and how much user's time and patience you want to take up on this test.
